name: Continous integration test

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Docker
        run: sudo apt-get install docker && sudo docker-compose up -d

      - name: Install Composer
        run: sudo docker exec -i php-unit-test composer install

      - name: Run Tests
        run: sudo docker exec -i php-unit-test vendor/bin/phpunit
